---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# detrendr

The goal of detrendr is to estimate smooth quantile trends in evenly spaced series. Missing values are allowed. 

# Installation

You can install the development version of detrendr from  [Github](https://github.com/halleybrantley/detrendr) with:

``` r 
library(devtools)
install_github("halleybrantley/detrendr")
```

## Example

Estimate the 5th and 20th quantile trends using a fixed value of the smoothing parameter $\lambda$. 

```{r example1, fig.width = 4}
library(devtools)
load_all()
n <- 100
x <- seq(1, n, 1)
y <- sin(x*2*pi/n) + rnorm(n, 0, .4)
lambda <- 10
k <- 3
tau <- c(0.05, .2)
trend <- get_trend(y, tau, lambda, k)
plot(y~x, type="l", col="grey")
lines(trend[,1]~x, col="red")
lines(trend[,2]~x, col="blue")
```

Use eBIC criterion to choose smoothing parameter

```{r BIC, echo = FALSE, include = FALSE}

trend_fit <- get_trend_BIC(y, tau, k, plot_lambda = TRUE)
trend <- trend_fit$trend
plot(y~x, type="l", col="grey")
lines(trend[,1]~x, col="red")
lines(trend[,2]~x, col="blue")
```


